/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Snoowrap: typeof import('snoowrap')['default']
  const snoowrap: typeof import('Snoowrap')['default']
}
